# Generated by Django 3.0.8 on 2020-09-30 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='학정번호')),
                ('faculty', models.CharField(max_length=30, verbose_name='학부대학')),
                ('department', models.CharField(max_length=30, verbose_name='전공')),
                ('semester', models.CharField(max_length=30, verbose_name='학기')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('name', models.CharField(max_length=30, verbose_name='교과목명')),
                ('credit', models.IntegerField(verbose_name='학점')),
                ('classroom', models.CharField(max_length=50, verbose_name='강의실')),
                ('time', models.CharField(max_length=50, verbose_name='강의시간')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='학과명')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('department', models.CharField(blank=True, max_length=30, null=True, verbose_name='소속')),
                ('office', models.CharField(blank=True, max_length=30, null=True, verbose_name='연구실')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField(verbose_name='정원')),
                ('participants', models.IntegerField(verbose_name='참여 인원')),
                ('major_quota', models.IntegerField(verbose_name='전공자 정원')),
                ('include_second_major', models.BooleanField(verbose_name='복수전공 포함 여부')),
                ('max_mileage', models.IntegerField(verbose_name='최대 마일리지')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Lecture', verbose_name='과목')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(verbose_name='마일리지')),
                ('is_major', models.BooleanField(verbose_name='전공 여부')),
                ('is_included', models.BooleanField(verbose_name='전공자 정원 포함 여부')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('success', models.BooleanField(verbose_name='수강 여부')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='api.Lecture', verbose_name='과목')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True, verbose_name='학번')),
                ('grade', models.IntegerField(verbose_name='학년')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경일시')),
                ('lectures', models.ManyToManyField(related_name='users', to='api.Lecture')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.Major', verbose_name='전공')),
                ('second_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_users', to='api.Major', verbose_name='복수전공')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='api.Professor', verbose_name='담당교수'),
        ),
    ]
