# Generated by Django 3.0.8 on 2020-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.Lecture'),
        ),
    ]
